name: terraform-project-base-action
description: Begin a terraform project component
inputs:
  project:
    description: Project name this resource is part of
    required: true
  owner:
    description: Project owner/team
    required: true
  email:
    description: Project owner/team email address
    required: true
  remote_state_bucket:
    descripton: S3 bucket containing this projects remote state data (read-write)
    required: true
  remote_lock_table:
    description: DynamoDB Table for managing Terraform Locks
    required: true
  shared_state_key:
    description: S3 key containing Terraform Shared State data to read from (read-only)
    required: true
  workspace:
    description: Terraform Workspace to operate from
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
