name: terraform-project-base-action
description: Begin a terraform project component
inputs:
  project:
    description: Project name this resource is part of
    required: true
  owner:
    description: Project owner/team
    required: true
  email:
    description: Project owner/team email address
    required: true
  dev:
    description: Git branch pattern to deploy to dev environment
    default: 'develop'
  stage:
    description: Git branch pattern to deploy to stage environment
    default: 'master'
  prod:
    description: Git branch pattern to deploy to prod environment
    default: 'tag'
  workspace:
    description: Terraform Workspace to operate from.  In terraform this is accessible as terraform.workspace. By default the git branch pattern will decide which workspace to use.
    required: false
  tf_assume_role:
    description: Specify role that later actions should assume. Only actions designed to work with terraform-project-base will assume this role.
  remote_state_bucket:
    descripton: S3 bucket containing this projects remote state data (read-write)
    required: true
  remote_lock_table:
    description: DynamoDB Table for managing Terraform Locks
    required: true
  shared_state_key:
    description: S3 key containing Terraform Shared State data to read from (read-only)
    required: true
  plan:
    description: Skip the Terraform Plan portion of the build
    default: true
  debug:
    description: Enable action debugging
    default: false

outputs:
  - account_root_id
  - account_id
  - cluster_azs
  - cluster_cluster_name
  - cluster_ecr_repo
  - cluster_elk_endpoint
  - cluster_execution_role
  - cluster_execution_role_arn
  - cluster_id
  - cluster_private_subnets
  - cluster_public_subnets
  - cluster_region
  - cluster_security_groups
  - cluster_service_namespace_id
  - cluster_vpc_id
  - dns_zone_id_private
  - dns_zone_id_public
  - dns_zone_id_service
  - external_id
  - network_azs
  - network_cidr_block
  - network_dns_delegation_id
  - network_igw_id
  - network_power_user_role_arn
  - network_private_route_tbl
  - network_private_subnets
  - network_public_route_tbl
  - network_public_subnets
  - network_region
  - network_vpc_id
  - project_name
  - project_owner
  - project_email
  - route_table_id_private
  - route_table_id_public
  - setting_admin
  - setting_admin_email
  - setting_admin_key
  - setting_admin_key_name
  - setting_domain_name
  - setting_elkendpoint
  - setting_enable_couchdb
  - setting_enable_finance-cst
  - setting_enable_sa_eks
  - setting_enable_vpc_flow_logs
  - setting_enable_vpn_gateway
  - setting_enable_wptest
  - setting_s3_remotestate_bucket_id
  - setting_sa_eks_enable
  - setting_subnet_prefix
  - sns_alerts
  - sns_notifications
  - subnet_id_private
  - subnet_id_public
  - user_id
  - user_arn

runs:
  using: 'docker'
  image: 'Dockerfile'
